Criar repositorio que implementa a interface de operacoes crud utilizando o orm linq2db
pa-pcosta/InventSoftware_CRUD pull request #18
Opened 2023-12-27 17:04 UTC by pa-pcosta

2023-12-27 19:25 UTC, marcofeitosa requested changes

2023-12-27 19:25 UTC, marcofeitosa commented on src/InfraestruturaDeDados/Repositorios/RepositorioLinq2DB.cs
> +                    var query = from produtoTapecaria in tb_Tapecaria
Tem forma melhor de implementar essa busca

2023-12-27 19:25 UTC, marcofeitosa commented on src/Dominio/ConstantesGlobais.cs
> +        public static readonly string sqlServerConnectionString = "Data Source=DESKTOP-DK6NM39;Initial Catalog=Controle_De_Estoque;User ID=sa;Password=sap@123;TrustServerCertificate=true";
Por que salvar a connection string em uma constante global ao invés de usar a app.config?

2023-12-27 19:25 UTC, marcofeitosa commented on src/InfraestruturaDeDados/Repositorios/RepositorioLinq2DB.cs
> +                    var query = from produtoTapecaria in tb_Tapecaria
Também tem forma melhor de implementar aqui

2023-12-28 11:49 UTC, pa-pcosta commented on src/Dominio/ConstantesGlobais.cs
> +        public static readonly string sqlServerConnectionString = "Data Source=DESKTOP-DK6NM39;Initial Catalog=Controle_De_Estoque;User ID=sa;Password=sap@123;TrustServerCertificate=true";
antes estava usando dessa forma mas me parecia estranho fazer aquela chamada enorme (ConfigurationManager.ConnectionStrings["SQL_Server_Controle_De_Estoque"].ConnectionString). Mas pensando melhor essa forma parece mais adequada. Vou corrigir.

2023-12-28 11:52 UTC, marcofeitosa commented on src/Dominio/ConstantesGlobais.cs
> +        public static readonly string sqlServerConnectionString = "Data Source=DESKTOP-DK6NM39;Initial Catalog=Controle_De_Estoque;User ID=sa;Password=sap@123;TrustServerCertificate=true";
A chamada é realmente maior e parece mais feia, mas estando na app.config tem vantagens de segurança e tals que acabam compensando

2023-12-28 17:01 UTC, marcofeitosa approved these changes

2023-12-28 17:01 UTC, merged